output "id" {
  description = "The API's ID."
  value       = module.api.api_id
}

output "endpoint" {
  description = "The `execute-api` endpoint generated by AWS. It stays set even with `disable_default_endpoint`, but in that case it does not answer."
  value       = module.api.api_endpoint
}

output "invoke_url" {
  description = "The stage's invocation URL. It is the one to use in the clients."
  value       = module.api.stage_invoke_url
}

output "arn" {
  description = "The API's ARN."
  value       = module.api.api_arn
}

output "execution_arn" {
  description = "The execution ARN, the base of the invocation permissions' source ARNs."
  value       = module.api.api_execution_arn
}

output "domain_name" {
  description = "The custom domain's target domain name, the one to point at in DNS. Null without a custom domain."
  value       = var.domain == null ? null : module.api.domain_name_target_domain_name
}

output "access_log_group_name" {
  description = "Name of the access logs' log group. Null when they are disabled or sent to an external destination."
  value       = var.access_logs.enabled && var.access_logs.destination_arn == null ? module.api.stage_access_logs_cloudwatch_log_group_name : null
}

output "invoked_function_keys" {
  description = <<-EOT
    The keys of the functions this API can invoke, deduplicated.

    It is there to verify that a function behind several routes receives a single permission,
    and that the authorizer is included: in the previous wiring this deduplication was a
    three-level `flatten` inside a single local.
  EOT
  value       = sort(tolist(local.invoked_functions))
}

output "route_authorization" {
  description = <<-EOT
    The effective authorization type for every route, derived from the authorizer.

    It is the output to look at in a review: it says which routes are public without having
    to work it out by cross-referencing two fields.
  EOT
  value       = { for k, r in local.routes : k => r.authorization_type }
}

output "alarm_arns" {
  description = "The created alarms' ARNs, by type. An empty map when the alarms are disabled."
  value = var.alarms.enabled ? tomap({
    server_errors = aws_cloudwatch_metric_alarm.server_errors[0].arn
    latency       = aws_cloudwatch_metric_alarm.latency[0].arn
  }) : tomap({})
}
