variable "name" {
  description = "The site's name, used for the bucket and the distribution. If `prefix` is set the final name is `<prefix>-<name>`."
  type        = string
}

variable "prefix" {
  description = "Naming prefix, typically `<project>-<environment>`."
  type        = string
  default     = null
}

variable "comment" {
  description = "The CloudFront distribution's comment, visible in the console."
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags applied to every resource the module creates."
  type        = map(string)
  default     = {}
}

variable "aliases" {
  description = <<-EOT
    Alternative domain names for the distribution. They require `certificate_arn`.
  EOT
  type        = list(string)
  default     = []
}

variable "certificate_arn" {
  description = <<-EOT
    ACM certificate for the aliases. **It must be in us-east-1**: CloudFront does not accept
    certificates from other regions, and the error you get otherwise does not say so.

    The module does not create certificates: validating them has timings and DNS dependencies
    that do not belong to a distribution's lifecycle.
  EOT
  type        = string
  default     = null

  validation {
    condition     = var.certificate_arn == null || can(regex("^arn:aws[a-z-]*:acm:us-east-1:", coalesce(var.certificate_arn, "x")))
    error_message = "The certificate must be in us-east-1: CloudFront does not accept certificates from other regions."
  }
}

variable "web_acl_arn" {
  description = <<-EOT
    WAFv2 WebACL to associate with the distribution. It must be of `CLOUDFRONT` scope, whose
    ARN contains `global/webacl`.

    It is here and not on `modules/http-api` for a technical reason: **WAFv2 cannot be
    associated with an HTTP API Gateway**. It only supports REST APIs, and requires the
    stage's ARN. To protect an HTTP API with the WAF you need CloudFront in front.
  EOT
  type        = string
  default     = null

  validation {
    condition     = var.web_acl_arn == null || can(regex("global/webacl/", coalesce(var.web_acl_arn, "x")))
    error_message = "The WebACL must be of CLOUDFRONT scope: its ARN contains 'global/webacl/'. A REGIONAL ACL cannot be associated with CloudFront."
  }
}

variable "zone_id" {
  description = "The Route53 zone in which to create the alias records for the `aliases`. Null creates no records."
  type        = string
  default     = null
}

variable "spa" {
  description = <<-EOT
    Preset for a single page application: the origin's 403 and 404 responses are rewritten to
    200 on `/index.html`, so that client-side routing works on deep URLs.

    **Leave it disabled for asset buckets.** With the preset on, a missing object returns the
    index with a 200 code: an asset that does not exist becomes indistinguishable from one
    that does, and the clients never find out.
  EOT
  type        = bool
  default     = false
}

variable "default_root_object" {
  description = "The object served on the root."
  type        = string
  default     = "index.html"
}

variable "price_class" {
  description = "Price class. `PriceClass_100` covers Europe and North America and costs less."
  type        = string
  default     = "PriceClass_100"

  validation {
    condition     = contains(["PriceClass_All", "PriceClass_200", "PriceClass_100"], var.price_class)
    error_message = "price_class must be 'PriceClass_All', 'PriceClass_200' or 'PriceClass_100'."
  }
}

variable "cache_policy_id" {
  description = "Cache policy of the default behavior. The default is AWS's managed `CachingOptimized`."
  type        = string
  default     = "658327ea-f89d-4fab-a63d-7e88639e58f6"
}

variable "response_headers_policy_id" {
  description = <<-EOT
    Response headers policy. The default is AWS's managed `SecurityHeadersPolicy`, which adds
    HSTS, `X-Content-Type-Options`, `X-Frame-Options`, `Referrer-Policy` and a basic
    `Content-Security-Policy`.

    Passing `null` disables it: those headers are free and have no downsides on a static site,
    so giving them up is worth an explicit choice.
  EOT
  type        = string
  default     = "67f7725c-6f97-4210-82d7-5512b31e9d03"
}

variable "allowed_methods" {
  description = "HTTP methods accepted by the default behavior. A static site needs no more than GET, HEAD and OPTIONS."
  type        = list(string)
  default     = ["GET", "HEAD", "OPTIONS"]
}

variable "custom_error_responses" {
  description = "Custom error responses, on top of the ones generated by the `spa` preset."
  type = list(object({
    error_code            = number
    response_code         = optional(number)
    response_page_path    = optional(string)
    error_caching_min_ttl = optional(number)
  }))
  default = []
}

variable "logging" {
  description = "The distribution's access logs towards a bucket. The bucket must have ACLs enabled, which is why it is not the site's own."
  type = object({
    bucket          = string
    prefix          = optional(string)
    include_cookies = optional(bool, false)
  })
  default = null
}

variable "bucket_versioning_enabled" {
  description = "Versioning of the content bucket."
  type        = bool
  default     = true
}

variable "bucket_force_destroy" {
  description = "Lets Terraform delete the bucket even if it contains objects. Necessary in throwaway environments."
  type        = bool
  default     = false
}

variable "wait_for_deployment" {
  description = "Waits for the distribution to be fully propagated. `false` makes applies much faster during development."
  type        = bool
  default     = false
}
